server:
  port: 8080
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: catalogRoute 
          uri: http://localhost:8082/ 
          predicates: 
            - Path=/catalog/**
        - id: movieRoute 
          uri: http://localhost:8084/ 
          predicates:
            - Path=/movies/**
